// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SamsWarehouse.Models.Data;

#nullable disable

namespace SamsWarehouse.Migrations
{
    [DbContext(typeof(SQLDBContext))]
    partial class SQLDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SamsWarehouse.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SamsWarehouse.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("SamsWarehouse.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("datetime2");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("SamsWarehouse.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("images")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Details = "Lindt EXCELLENCE, crafted with the finest cocoa creates rich flavours, a smooth texture and silky sheen. A treat for the senses. Discover the finest dark chocolate.nnExpertly crafted from the finest cocoa beans, this full-bodied chocolate is masterfully balanced, boasting deep roasted cocoa flavours, which gives away to subtle fruit undertones.nnLindt EXCELLENCE 70% Cocoa Dark Chocolate 100gnnEnliven your senses with the ultimate chocolate luxury, EXCELLENCEnnDiscover the expertise and craftsmanship of our Lindt Master Chocolatiers since 1845nnBlends the most aromatic, cocoa beans with the finest ingredientsnnRich and refined chocolate of intense flavour and elegant texture",
                            Ingredients = "IngredientsnCocoa Mass, Sugar, Cocoa Butter, Vanilla.",
                            Price = 4.25,
                            Size = "100g",
                            Title = "Lindt Excellence 70% Cocoa Block",
                            images = 6
                        },
                        new
                        {
                            Id = 10,
                            Details = "PRIMO SHORT-CUT Rindless Bacon is the leanest of them all.Lean round pieces of bacon from top grade loin for those who enjoy a meatier, leaner flavour preference.nnWake up happy, Australias Favourite Bacon is Sizzling with Flavour! nPrimo Bacon is gluten free with no artificial colours or flavours.",
                            Ingredients = "IngredientsnPork (89%), Water, Curing Premix [Salt, Sugar, Mineral Salts (451, 4150), Antioxidant (316), Preservative (250)], Naturally Wood Smoked.",
                            Price = 5.0,
                            Size = "175g",
                            Title = "Primo Short cut rindless Bacon",
                            images = 1
                        },
                        new
                        {
                            Id = 11,
                            Details = "Helgas Wholemeal Grain Loaf Sliced Bread contains fibre and protein with no artificial colours, flavours or preservatives. Enjoy toasted with your favourite spread for a quick breakfast.nnYou can never go wrong with Helga's Wholemeal Grain Loaf Sliced Bread. A fantastic breakfast option for everyone to enjoy, simply spread with butter and add your favourite toppings or toast with peanut butter for a quick delicious bite. The options are endless.nn Source of proteinnn Good source of fibrenn No artificial coloursnn No artificial flavoursnn No artificial preservatives",
                            Ingredients = "IngredientsnWholemeal wheat flour (53%), water, whole grains (10%) (kibbled wheat, malted wheat flakes, kibbled rye, kibbled triticale), yeast, linseeds, vinegar, wheat bran, wheat flour, canola oil, iodised salt, wheat gluten, cultured wheat flour, soy flour, vegetable emulsifiers (481, 471, 472e), malted barley flour, vitamins (thiamin, folic acid).",
                            Price = 3.7000000000000002,
                            Size = "1",
                            Title = "Helga's Wholemeal",
                            images = 4
                        },
                        new
                        {
                            Id = 12,
                            Details = "San Remo Linguine contains no artificial colourings, flavourings or preservatives. Cooks in 10 minutes.",
                            Ingredients = "IngredientsnDurum Wheat Semolina.",
                            Price = 1.95,
                            Size = "500g",
                            Title = "San Remo Linguine Pasta No 1",
                            images = 2
                        },
                        new
                        {
                            Id = 13,
                            Details = "- 15 Fish Fingers Per Packn- Made from Hoki Fishn- MSC Certifiedn- Good Source of Omega-3n- No Artificial Colours, Flavours or PreservativesnSimply delicious! Since their Australian debut in 1956, Birds Eye iconic Fish Fingers have become a family favourite. Made from Hoki, with no artificial colours, flavours or preservatives. They're coated in a delicioius, crunchy crumb, making them a hit with the crew everytime!",
                            Ingredients = "Ingredientsn*hoki* (51%), *wheat* flour, water, canola oil, maize flour, *wheat* starch, maize starch, salt, sugar, *wheat* gluten, yeast, acidity regulator (451, 450). *Contains fish and wheat.*",
                            Price = 4.5,
                            Size = "375g",
                            Title = "Birds Eye Fish Fingers",
                            images = 10
                        },
                        new
                        {
                            Id = 14,
                            Details = "Red Washed PotatoesnnIn Season: All YearnnRed Washed Potatoes have pink, smooth skin with creamy white flesh, they are high in moisture and low in starch which makes them hold their shape well when cooked, making them ideal for roasting.",
                            Price = 4.0,
                            Size = "1kg",
                            Title = "Red potato washed",
                            images = 1
                        },
                        new
                        {
                            Id = 15,
                            Details = "The ultimate tangy apple! Firm, crunchy, and tart making the Granny Smith a great snack, and ideal for baking and cooking.nnHow to Pick:nApples should be bright and crunchy, with a tight skin and juicy flesh. Our apples have a natural shine and no added wax.nnnStoring your apples in the fridge will keep them crisp and fresh for longer.nConsume apples within 2 weeks for the best eating experience.nnnOur hand picked apples are 100% Australian grown. Our expert growers pick them from trees in the colder climate regions of Australia to ensure they have the best flavour, colour and firmness.",
                            Price = 5.5,
                            Size = "1kg",
                            Title = "Granny Smith Apples",
                            images = 1
                        },
                        new
                        {
                            Id = 16,
                            Details = "Round in shape, with a bright red shiny skin and red pulp and whitish seeds. The tomato is actually a fruit but is considered a vegetable because of its uses. ",
                            Price = 5.9000000000000004,
                            Size = "500g",
                            Title = "Fresh tomatoes",
                            images = 1
                        },
                        new
                        {
                            Id = 17,
                            Details = "Woolworth's Select Carrot are selected fresh from Australian farms, the ever versatile carrots is perfect for cooking or eating raw as a fresh snack. Edible portion includes flesh only. ",
                            Price = 2.0,
                            Size = "1kg",
                            Title = "Carrots",
                            images = 1
                        },
                        new
                        {
                            Id = 18,
                            Details = "Large oval fruit with a thick green skin and a sweet watery pink to red flesh with usually many seeds.nOften the deeper colored the flesh, the sweeter the taste. Watermelon's flesh contains about 6% sugar and it is comprised primarily of water. nnnAll year.nnnWatermelon is best utilized in fresh, uncooked applications. Its flesh can be cubed, balled, sliced into wedges or pureed. The large shell can be carved into a decorative basket and used as a natural vessel for serving beverages or salads. Pureed it can be used to flavor drinks or to make granitas, sorbets and chilled soups. Its sweet flavor pairs well with cucumber, arugula, basil, mint, citrus juice, peanuts, coconut, pecans and robust cheeses such as feta, romano and parmesan. Though not commonly consumed as a result of its bitter flavor the rind of the Watermelon is edible and can be grilled, stewed, stir-fired or pickled. The seeds as well are edible and can be roasted or dried and seasoned. Unlike most other melons, refrigerate Watermelon for best flavor. ",
                            Price = 6.5999999999999996,
                            Size = "Whole",
                            Title = "Watermelon",
                            images = 1
                        },
                        new
                        {
                            Id = 19,
                            Details = "Red onions have burgundy red skins and red tinged flesh. Spanish type red onions are large and round, while Californian red onions tend to be flatter and milder. They are mild, sweet and juicy and are delicious eaten raw in salads, used as a garnish or added to sandwiches.",
                            Price = 3.5,
                            Size = "1kg",
                            Title = "Red onion",
                            images = 1
                        },
                        new
                        {
                            Id = 2,
                            Price = 1.8999999999999999,
                            Size = "1 whole",
                            Title = "Cucumber",
                            images = 1
                        },
                        new
                        {
                            Id = 20,
                            Details = "Mornings taste better with Nutella!",
                            Ingredients = "IngredientsnINGREDIENTS: SUGAR, VEGETABLE OIL (PALM*), HAZELNUTS (13%), SKIM MILK POWDER (8.7%), FAT-REDUCED COCOA POWDER (7.4%), EMULSIFIER (LECITHINS) (SOY), FLAVOURING (VANILLIN). TOTAL MILK SOLIDS: 8.7%. TOTAL COCOA SOLIDS: 7.4%. *Sustainable and segregated certified palm oil.",
                            Price = 4.0,
                            Size = "400g",
                            Title = "Nutella jar",
                            images = 7
                        },
                        new
                        {
                            Id = 21,
                            Details = "Iceberg Lettuce is round in shape, with packed layers ofncrisp green leaves. The heads are firm and tightly packed with ancentral core or heart. The leaves are crunchy and have a mild flavour.nThe outer leaves are a darker green; the central leaves are pale green.nThe leaves are cupped, hold their shape and can be used to hold fillings.nnAvailabilitynAll year.nnStorenRefrigerate in reusable plastic bags, or store in the crisper.nAvoid squashing the lettuce. Alternatively, if the lettuce roots are stillnattached, stand the lettuce in a jar with the roots in water,nand do not refrigerate.nnWays to eatnLettuce is used raw in salads, sandwiches and rolls.nLettuce leaves may also be used as wraps.nOlder leaves can be used in soups.",
                            Price = 2.5,
                            Size = "1",
                            Title = "Iceburg Lettuce",
                            images = 1
                        },
                        new
                        {
                            Id = 22,
                            Details = "Red Tip Bananas are great for breakfast and snacking occasions and are the perfect lunchbox addition. nnHow to Pick:nBananas that are yellow and lightly flecked with brown spots will be at their peak flavor. Bananas should be plump, firm, and brightly colored.nnnStore bananas at room temperature, where they will continue to ripen. If you refrigerate your bananas, they will stop ripening, but this will also make the skins go black. The fruit is still okay to eat, but will not be the best quality.nnnAustralian Red Tip Bananas are grown in Far North Queensland, near Innisfail.nnnBananas contain potassium for heathy muscle function, and are high in energy-supprting vitamin B6* nn*Based on one large cavendish banana, or 2 medium lady finger bananas (150g), as part of a healthy balanced diet",
                            Price = 4.9000000000000004,
                            Size = "1kg",
                            Title = "Red tipped bananas",
                            images = 1
                        },
                        new
                        {
                            Id = 23,
                            Details = "This is a variable weight product and is priced by $/kg. Once we've picked your item in store, we'll refund you for the difference between the weight paid and the weight received. Please advise in your personal shopper notes your preferred weight when reviewing your order at checkout. We will try our best to provide you with the requested weight.",
                            Price = 7.5,
                            Size = "1kg",
                            Title = "Free range chicken",
                            images = 2
                        },
                        new
                        {
                            Id = 24,
                            Details = "Cobram Estate Classic Flavour Intensity is crafted from olives grown in Australias leading groves on the banks of the Murray River. Our oil master skillfully combines the leading varieties from each estate to create a distinctive, first press Extra Virgin Olive Oil packed with appealing fresh fruity aromas and penetrating flavours. Why choose Cobram Estate Extra Virgin Olive Oil? 1.) Australia's freshest and most awarded Extra Virgin Olive Oil. 2.) We treat every olive just right, crushing and juicing within hours of picking, to capture the freshest antioxidants and other essential nutrients. 3.) Natural source of vitamin E, essential to protect body cells from free radical damage 4.) The result is a premium, healthy, value-packed extra virgin olive oil.",
                            Ingredients = "Ingredientsn100% Australian Extra Virgin Olive Oil",
                            Price = 8.0,
                            Size = "375ml",
                            Title = "Cobram EVOO",
                            images = 1
                        },
                        new
                        {
                            Id = 25,
                            Details = "a2 Milk Light is sourced from Australian dairy farmers and made with 100% Australian pure & natural milk from cows specially selected to produce milk with only the A2 beta-casein protein. a2 Milk Light contains only 1.3g of fat per 100ml and is a natural lower in fat alternative to full cream, with a creamy and smooth consistency. Its completely natural & the way milk is meant to be. Feel the a2 Milk difference - Naturally A1 protein free; No additives, no permeate; Made in Australia from 100% Australian ingredients.",
                            Ingredients = "IngredientsnReduced Fat Milk",
                            Price = 2.8999999999999999,
                            Size = "1 litre",
                            Title = "A2 light milk",
                            images = 1
                        },
                        new
                        {
                            Id = 26,
                            Details = "There for as soon as the toast pops up, Lurpak Spreadable Slightly Salted has become a modern classic and kitchen staple with its distinct Lurpak taste. It is perfect for mixing with fresh ingredients such as chives or parsley to create flavoured butters.",
                            Ingredients = "IngredientsnButter (64%), Canola Oil (26%), Water, Lactic Culture, Salt (0.9%), Vitamin D",
                            Price = 5.0,
                            Size = "250g",
                            Title = "Lurpak Salted Blend",
                            images = 1
                        },
                        new
                        {
                            Id = 27,
                            Details = "Sanitarium Weet-Bix Organic Breakfast Biscuits is 97% wholegrain, made from certified organic wheat, low in sugar and provides a source of fibre.nnnnnnnnnnnnnnnnnn97% wholegrainnnLow in SugarnnCertified Organic WheatnnSource of Fibre",
                            Ingredients = "IngredientsnOrganic Wholegrain Wheat (97%), Organic Sugar, Salt, Barley Malt Extract.",
                            Price = 5.3300000000000001,
                            Size = "750g",
                            Title = "Weet Bix Saniatarium Organic",
                            images = 7
                        },
                        new
                        {
                            Id = 28,
                            Details = "Colgate Total Original Toothpaste is clinically proven to protect teeth and gums from plaque bacteria for up to 12 hours, even after eating or drinking.",
                            Ingredients = "IngredientsnWater, Hydrated Silica, Glycerin, Sorbitol, PVM/MA Copolymer, Sodium Lauryl Sulphate, Flavour, Cellulose Gum, Carrageenan, Sodium Hydroxide, Sodium Fluoride, Sodium Saccharin, Triclosan, CI 77891.nnNO COLGATE TOOTHPASTE CONTAINS SUGAR.nView more",
                            Price = 3.5,
                            Size = "110g",
                            Title = "Colgate Total Toothpaste Original",
                            images = 4
                        },
                        new
                        {
                            Id = 29,
                            Details = "Sacla pasta sauce with Basil offers the unique flavour of traditional home-made Italian recipes. Delicious and rich tasty sauce made with the best quality ingredients like sweet whole cherry tomatoes. Buonissimo!",
                            Ingredients = "IngredientsnDiced Tomatoes, Tomato Juice, Tomato Paste, Cherry Tomatoes 12.5%, Sunflower Seed Oil, Onions, Carrots, Garlic, Celery, Basil 1.3%, Extra-Virgin Olive Oil,Fructose, Sea Salt, Modified Corn Starch (1412), Acidity Regulators: (270, 330), Firming Agent: (509).",
                            Price = 4.5,
                            Size = "420g",
                            Title = "Sacla Pasta Tomato Basil Sauce",
                            images = 1
                        },
                        new
                        {
                            Id = 3,
                            Details = "Made with no artificial colours or flavours, Golden Circle Australian Pieces Pineapple in Juice are the perfect ingredient for cooking, baking, mocktail and cocktail making. Add some pieces on top of ice cream or cake, add them to a fruit salad, or cook up a fantastic pineapple fried rice. Golden Circle Australian Pieces Pineapple in Juice contains 2 fruit serves per can (One serve of fruit = 150g. Aim for a variety of fruit each day.) and is conveniently chopped into pieces ready for cooking and eating. These pineapple pieces are tasty on pizza, with cooked meat, or baked into a fruity cake. On warmer days, make your own punch with lemonade, soda water and a tangy hit of Golden Circle Australian Pieces Pineapple in Juice.nnNo artificial colours or flavoursnnNo preservativesnn2 fruit serves per can (One serve of fruit = 150g. Aim for a variety of fruit each day.)nnMix with strawberries, lemonade and soda for the perfect holiday fruit punchnnConveniently chopped, ready to be used in dishes such as pineapple salsa or pineapple chicken",
                            Ingredients = "IngredientsnPineapple (70%), Reconstituted Pear Juice, Pineapple Juice or Reconstituted Pineapple Juice.",
                            Price = 3.25,
                            Size = "440g",
                            Title = "Golden Circle Pineapple Pieces in natural juice",
                            images = 5
                        },
                        new
                        {
                            Id = 30,
                            Details = "Smooth, sweet and perfectly balanced, generations of Aussies have grown up with Capilano Pure Honey.nMade by Aussie bees and hand harvested by their beekeepers, our signature blend of eucalypt and ground flora honey is the taste you know and love.",
                            Ingredients = "Ingredientsn100% Pure Australian Honey",
                            Price = 7.3499999999999996,
                            Size = "500g",
                            Title = "Capilano Squeezable Honey",
                            images = 2
                        },
                        new
                        {
                            Id = 31,
                            Details = "Strawberries, plump little hearts grown full and tender, red-ripe ready-to-love, and topped with a layer of velvety Chobani Greek Yogurt, for a nutritious snack bursting with flavour.nnChobani Greek Yogurt is deliciously simple. Made using just milk and cultures, which we triple strain using an authentic process so its naturally thick and creamy, then layered onto strawberry.nnnnStrained to be naturally thicknnHigh in natural proteinnnNo preservatives, artificial colours or flavoursnnSource of calciumnnContains Live & Active CulturesnnMade in Australia",
                            Ingredients = "IngredientsnSkim Milk, Strawberry (8%), Sugar, Water, Vegetable Gums (Pectin, Guar Gum, Locust Bean Gum), Natural Flavours, Fruit and Vegetable Concentrates, Acidity Regulators (Citric Acid, Sodium Citrate), Mineral Salt (Calcium Citrate), Live Cultures (Milk).",
                            Price = 1.5,
                            Size = "1",
                            Title = "Chobani Strawberry Yoghurt",
                            images = 6
                        },
                        new
                        {
                            Id = 32,
                            Details = "MILO is a nutrient rich, low GI choc malt powder drink providing kids the nourishing energy they need to take on the day. Simply add 3-heaped teaspoons of MILO to a glass of hot or cold skim milk for a delicious chocolate malt flavoured milk drink. MILO is great with breakfast, after school, before or after sport as a snack or as a hot chocolately malt drink after dinner. Made from four main ingredients: milk powder, malt barley, sugar and cocoa, MILO also contains 8 essential vitamins and minerals. Contains 10 serves of choc-malty goodness. Do Good Together. Did you know, our MILO tins are made from 100% reyclable materials. And approximately 80% of the energy powering our MILO factory comes from BIOENERGY, a renewable energy source. To find out more visit the MILO website. MILO and Banana Shake Serves: 2 Prep Time: 5 min Ingredients: 1 cup reduced fat milk 0.5 cup natural yoghurt 1/3 cup (40g) MILO 1 medium banana, chopped Method: 1. Combine all ingredients in a blender; blend until smooth, thick and creamy. 2. Pour into tall glasses and serve immediately. *When consumed as part of a healthy diet with a wide variety of foods.",
                            Ingredients = "IngredientsnExtract of Malt Barley Or Malt Barley and Rice (Total Extract 38%), Milk Solids, Sugar, Cocoa, Choc Malt Blend, Minerals (Calcium, Iron), Maltodextrin (Corn), Vitamins (C, B3, B6, B2, D, B12), Emulsifier ( Soy Lecithin) n Contains Gluten, Milk and SoynView more",
                            Price = 4.0,
                            Size = "200g",
                            Title = "Milo Chocolate Malt",
                            images = 6
                        },
                        new
                        {
                            Id = 33,
                            Details = "Mini Babybel Cheese Original is made with 155mL of milk, it contains a source of calcium.",
                            Ingredients = "IngredientsnMilk (98%), Salt, Bacterial Culture, Microbial Rennet.",
                            Price = 4.2000000000000002,
                            Size = "100g",
                            Title = "Babybel Mini",
                            images = 1
                        },
                        new
                        {
                            Id = 34,
                            Details = "South Cape Greek Style Fetta contains firm, crisp & slightly acidic flavour.",
                            Ingredients = "IngredientsnPasteurised Cows Milk, Salt, Mineral Salt (509), Starter Cultures, Non-animal Rennet.",
                            Price = 5.0,
                            Size = "200g",
                            Title = "South Cape Greek Feta",
                            images = 1
                        },
                        new
                        {
                            Id = 35,
                            Details = "With the abundance of clean air, rich earth and pristine water on our farms its no surprise that our free range hens produce such tasty, nutritous eggs. The Matuszny family are pasture based farmers who only produce and package the best free range eggs. Our eggs contain high quality protein and are a great source of Omega 3, folate and selenium with 11 vitamins & minerals.",
                            Price = 3.6000000000000001,
                            Size = "6 eggs",
                            Title = "Manning Valley 6-pk",
                            images = 4
                        },
                        new
                        {
                            Id = 36,
                            Details = "Chunk style pieces of succulent tuna in springwater with a delicate flavour.nn- Good Source of Omega-3n- 98% Fat Freen- All Natural Ingredientsn- MSC certifiednnCombine with reduced fat mayonnaise, corn kernels and sliced celery and serve in a pita pocket.",
                            Ingredients = "IngredientsnPurse seine caught skipjack *tuna* (Katsuwonus pelamis) (65%), springwater, salt. *Contains fish.*",
                            Price = 1.5,
                            Size = "95g",
                            Title = "John West Tuna can",
                            images = 5
                        },
                        new
                        {
                            Id = 37,
                            Details = "Arnott??s Shapes Originals are an Aussie favourite savoury biscuit snack. Arnott??s Shapes Original Cheddar offer a mild cheddar flavour on a crisp and crunchy cracker base. Oven baked, not fried, and foil-wrapped for freshness.nnArnott??s Shapes Originals are big on crunch and even bigger on taste ?? and perfect for any occasion! These cheddar cheese crackers are delicious oven-baked crackers with loads of flavour you can see, and no artificial colours or preservatives.nnWhether you??re sharing with friends at the park or looking for a fun afternoon snack with flavours that your whole family will love, Arnott??s Shapes Original Cheddar biscuits are the perfect flavoured cracker. Foil-wrapped for freshness, they??re a go-to savoury cravings-buster for any occasion. Bags of flavour in every box, no matter which flavour you savour!nnA mild cheddar flavour on a crisp, crunchy cracker base.nnFlavour you can see.nnFoil-wrapped for freshness.nnOven baked, not fried.nnMade in Australia.",
                            Ingredients = "IngredientsnWheat Flour, Cheese (15%) (Milk Solids, Salt), Vegetable Oil, Salt, Yeast, Yeast Extract (Contains Barley), Malt Extract (From Barley), Wheat Starch, Sugar, Natural Flavour, Baking Powder, Worcestershire Sauce. Milk Solids. Spice, Vegetable Extract, Emulsifier (Soy Lecithin), Antioxidants (E307b From Soy, E304).",
                            Price = 2.0,
                            Size = "175g",
                            Title = "Cheddar Shapes",
                            images = 10
                        },
                        new
                        {
                            Id = 38,
                            Details = "Primo English Style Leg Ham is lightly seasoned and unsmoked for an authentic ham flavour. Serve on crusty bread with cheese and mustard.",
                            Ingredients = "IngredientsnPork, Water, Acidity Regulators (326, 325, 262), Cure [Salt, Mineral Salts (451, 450), Sugar, Antioxidant (316), Preservative (250), Natural Flavours].",
                            Price = 3.0,
                            Size = "100g",
                            Title = "Primo English Ham",
                            images = 2
                        },
                        new
                        {
                            Id = 39,
                            Price = 6.0,
                            Size = "2 litre",
                            Title = "Berri Orange Juice",
                            images = 1
                        },
                        new
                        {
                            Id = 4,
                            Details = "Experience the unbeatable deliciousness of Arnotts Scotch Finger, a sweet biscuit preferred for its melt-in-the-mouth crumbliness and heavenly buttery taste. Snap, dunk and enjoy  its one of Australias favourite biscuits for a reason!nnInject a bit of fun into your morning with an Arnotts Scotch Finger, a sweet biscuit made to snap and dunk in your favourite cuppa. Its the perfect choice for an indulgent me-time treat.nnThe original Arnotts Scotch Finger.nnDunkable.nnSnap and share.nnNo artificial colours, flavours or preservatives.nnAussie made, Aussie loved.",
                            Ingredients = "IngredientsnWheat Flour, Sugar, Butter (Cream (from Milk), Salt), Vegetable Oil, Condensed Milk, Salt, Eggs, Baking Powder, Emulsifier (Soy Lecithin), Antioxidant (E307b from Soy).",
                            Price = 2.8500000000000001,
                            Size = "250g",
                            Title = "Arnott's Scotch Finger",
                            images = 8
                        },
                        new
                        {
                            Id = 40,
                            Details = "Vegemite B Vitamins for vitality.nStart happy with Vegemite.",
                            Ingredients = "IngredientsnYeast Extract (from Yeast Grown on Barley and Wheat), Salt, Mineral Salt (508), Malt Extract (from Barley), Colour (150c), Flavours, Niacin, Thiamine, Riboflavin, Folate.",
                            Price = 6.0,
                            Size = "380g",
                            Title = "Vegemite",
                            images = 3
                        },
                        new
                        {
                            Id = 41,
                            Details = "Deliciously smooth and creamy Cadbury Dairy Milk milk chocolatenCadbury Dairy Milk milk chocolate block is Australia's favourite chocolate. It has 'the equivalent of a glass and a half of full cream milk in every 200g of Cadbury Dairy Milk milk chocolate'. Cadbury is perfect for treating yourself and sharing among family and friends. Also available in a 50g bar, 180g multipack and 350g block.",
                            Ingredients = "IngredientsnFull Cream Milk, Sugar, Cocoa Butter, Cocoa Mass, Milk Solids, Emulsifiers (Soy Lecithin, 476), Flavours.",
                            Price = 5.0,
                            Size = "200g",
                            Title = "Cadbury Dairy Milk",
                            images = 1
                        },
                        new
                        {
                            Id = 42,
                            Details = "Each chip is cooked and seasoned to perfection to create the classic salted taste that has become so richly embedded into the memories of families all over Australia. The Most Iconic Crinkle Cut Chips Around.  Smith's Original Chips are celebrating 90 years of being a household staple and has continued to capture the hearts and tongues of Aussies for generations.nnAustralian-made and Aussie ProudnOur Smith's Chips are made from 100% Australian potatoes, grown by Aussie farmers - including a family-run farm that's been supplying us for over 50 years.nnIn 1931, Smith's took the humble potato and created the original crinkle-cut potato chip recipe we all know and love today. Affectionately known as 'the People's Chip', our national heritage is something we are very proud to celebrate.nnPotato Snacks to Accompany Your Outdoor ActivitiesnThere is no better snack when watching the footy grand final or sprawling across the green for a picnic. They're perfect for indulging after a hard day's work and make the ideal school lunch snacks for your kids.nnAn Unbelievably Good but Gluten Free SnacknSmith's Original Crinkle Cut Chips are free from any hidden nasties! No artificial flavours, colours or even gluten means that anyone can enjoy the classic crunch & unbeatable original flavour that only a Smith's potato chip can bring!nnWhilst some things have changed since 1931, one thing remains the same, Smith's are still the original and the best!nnYou know you love 'em.nnThey're the nostalgic Aussie flavour that's made from local ingredients right on your doorstep.nnNo artificial flavours or colours mean that theyre perfect as school lunch snacks for your kids.nnAs a gluten free snack, anyone can enjoy the classic crinkle cut crunch and Smith's Original flavour.nnThere is no better snack when watching the footy grand final or sprawling across the green for a picnic.nnThey're the ideal snack to come home to after a long day's work",
                            Ingredients = "IngredientsnPotatoes (64%), Canola Oil, Sunflower Oil, Salt, Antioxidants (Tocopherols, Ascorbic Acid, Rosemary Extract, Citric Acid).",
                            Price = 3.29,
                            Size = "170g",
                            Title = "Smith's Original Share Pack Crisps",
                            images = 4
                        },
                        new
                        {
                            Id = 43,
                            Details = "One of the most timeless soup flavours, Heinz Classic Creamy Tomato Soup is a great light meal choice. Serve with a swirl of cream and some fresh basil or parsley. This delicious soup contains no preservatives or artificial flavours, and is 98% fat free too. Designed to be a quick lunch or dinner option, Heinz Classic Creamy Tomato Soup is perfect with a side of crusty bread. If you've got some more time in the evenings, this soup can also be used as the base of a pasta sauce.nnCreamy tomato soupnnNo preservativesnn98% fat freennNo artificial flavoursnn3 serves of veg per 265g serve (One serve of vegetables = 75g. Aim for a variety of vegetables each day.)",
                            Ingredients = "IngredientsnTomatoes (90%), Cream (3.4%) (Milk), Sugar, Maize Thickener (1412), Milk, Salt, Cornflour, Butter (Milk), Acidity Regulator (Sodium Bicarbonate), Spice, Natural Flavour.nnContains: Milk.nView more",
                            Price = 2.5,
                            Size = "535g",
                            Title = "Heinz Tomato Soup",
                            images = 9
                        },
                        new
                        {
                            Id = 5,
                            Details = "An iconic Aussie treat, Arnott??s Tim Tam Original is a mouth-watering combination of crunchy biscuit, luscious cream centre, wrapped in a smooth milk chocolate coating . It??s easy to see why Tim Tam is Australia??s most-loved chocolate biscuit.nnFind your moment of indulgence with Arnott??s Tim Tam Original. Made with irresistible real chocolate, these biscuits are the perfect way to indulge in the afternoon or unwind at the end of a long day. What more could you wish for?nnAustralia??s most-loved chocolate biscuits.nnMade with irresistible real chocolate.nnFor your moment of afternoon indulgence.nnThere is no substitute.nnMade in Australia.",
                            Ingredients = "IngredientsnBiscuits: Milk Chocolate (38%) (Sugar, Milk Solids,, Cocoa Butter, Cocoa Mass, Vegetable Oil, Emulsif,iers (Soy Lecithin, E476), Flavour), Wheat Flour,,Sugar, Vegetable Oil (Emulsifier (Soy Lecithin), A,ntioxidant (E307b From Soy)), Golden Syrup, Food C,o",
                            Price = 3.6499999999999999,
                            Size = "200g",
                            Title = "Original Tim Tams Choclate",
                            images = 5
                        },
                        new
                        {
                            Id = 6,
                            Details = "Experience the smooth taste of Moccona Classic Medium Roast. Its full-bodied flavour and rich aroma make it the perfect coffee to enjoy everyday.",
                            Ingredients = "Ingredientsn100% Coffee beans.",
                            Price = 6.0,
                            Size = "100g",
                            Title = "Moccana Classic Instant Medium Roast",
                            images = 4
                        },
                        new
                        {
                            Id = 7,
                            Details = "Coca-Cola Classic Soft Drink Bottle 2LnnNothing beats the taste of Coca-Cola Classic. It's the perfect companion whether youre on the go, relaxing at home, enjoying with friends or as a drink with your meal. Refresh yourself with the authentic Coke taste. Designed to go with everything, the taste of Classic Coca-Cola has remained unchanged for more than 130 years. Coca-Cola soft drink is available in cans, mini cans, single serve and sharing size bottles as well as multipacks.nnClassic Coca-Cola TastennServe Drink Cold for Maximum RefreshmentnnA Quality Product of The Coca-Cola Companynn2L Soft DrinknnPerfect for drinking on the go, having with a meal or relaxing with at home.",
                            Ingredients = "IngredientsnCarbonated Water, Sugar, Colour (150d), Food Acid (338), Flavour, Caffeine.",
                            Price = 2.8500000000000001,
                            Size = "2 litre",
                            Title = "Coca Cola",
                            images = 3
                        },
                        new
                        {
                            Id = 8,
                            Ingredients = "IngredientsnMilk, Salt, Cultures, Enzyme (Non-Animal Rennet).",
                            Price = 4.0,
                            Size = "250g",
                            Title = "Bega Farmers Tasty",
                            images = 5
                        },
                        new
                        {
                            Id = 9,
                            Details = "The Original Philadelphia Cream Cheese is made fresh and creamy, perfect as a spread or as an ingredient in some of your favourite desserts.",
                            Ingredients = "IngredientsnMilk, Cream (from Milk), Milk Solids, Salt, Vegetable Gum (Locust Bean), Starter Culture.",
                            Price = 4.2999999999999998,
                            Size = "250g",
                            Title = "Philadelphia Original Cream Cheese",
                            images = 3
                        });
                });

            modelBuilder.Entity("SamsWarehouse.Models.Cart", b =>
                {
                    b.HasOne("SamsWarehouse.Models.AppUser", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SamsWarehouse.Models.CartItem", b =>
                {
                    b.HasOne("SamsWarehouse.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SamsWarehouse.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SamsWarehouse.Models.AppUser", b =>
                {
                    b.Navigation("Carts");
                });

            modelBuilder.Entity("SamsWarehouse.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("SamsWarehouse.Models.Product", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
